FROM postgres:11-alpine

ARG NETWORK=mainnet

RUN wget https://filetransfer.io/data-package/h4EpjN5H -O latestsnap.sql.gz && \
    mkdir -p /docker-entrypoint-initdb.d && \
    mv latestsnap.sql.gz /docker-entrypoint-initdb.d
